apiVersion: v1
kind: List
items:
  - apiVersion: "external-secrets.io/v1beta1"
    kind: "ClusterSecretStore"
    metadata: 
      name: "aws-secret-store" 
    spec: 
      provider: 
        aws: 
          service: "SecretsManager"
          region: {{ .Values.awsRegion }}
          auth: 
            jwt: 
              serviceAccountRef: 
                name: "external-secrets-service-account"
                namespace: "external-secrets"
  - apiVersion: v1
    kind: Secret
    metadata:
      name: github-auth
      namespace: argocd
      labels:
        argocd.argoproj.io/secret-type: repository
    stringData:
      url: {{ .Values.argoGithubUrl }} 
      username: not-used
  - apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: "github-auth"
      namespace: argocd
    spec:
      secretStoreRef:
        name: aws-secret-store
        kind: ClusterSecretStore
      refreshInterval: "60s"
      target:
        name: github-auth
        creationPolicy: 'Merge'
        deletionPolicy: "Retain"
      data:
        - secretKey: password
          remoteRef:
            key:  {{ .Values.githubTokenSecretPath }}